route:
  receiver: 'slack'

receivers:
  - name: 'slack'
    slack_configs:
      - send_resolved: true
        text: "{{ .CommonAnnotations.description }}"
        username: 'Prometheus'
        channel: '#as-notification-test'
        api_url: 'https://hooks.slack.com/services/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'
